export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const PASSWORD_RESET_INITIATE = "PASSWORD_RESET_INITIATE";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";

export const GET_ALL_AREAS_START = "GET_ALL_AREAS_START";
export const GET_ALL_AREAS_SUCCESS = "GET_ALL_AREAS_SUCCESS";
export const GET_ALL_AREAS_FAIL = "GET_ALL_AREAS_FAIL";

export const GET_ALL_PLACES_START = "GET_ALL_PLACES_START";
export const GET_ALL_PLACES_SUCCESS = "GET_ALL_PLACES_SUCCESS";
export const GET_ALL_PLACES_FAIL = "GET_ALL_PLACES_FAIL";
// export const LOGOUT_START = "LOGOUT_START";

export const COMPONENT_CHANGE = "COMPONENT_CHANGE";
export const SELECTED_PLACE = "SELECTED_PLACE";
export const GET_ALL_AVAILABLE_SLOTS = "GET_ALL_AVAILABLE_SLOTS";
export const CHANGE_STEP = "CHANGE_STEP";
